{% set version = "0.12.1" %}

package:
  name: fermipy
  version: {{version}}

source:
  fn: fermipy-{{version}}.tar.gz
  url: https://pypi.io/packages/source/f/fermipy/fermipy-{{ version }}.tar.gz 
  md5: 2579ba6e715f1a5a8266634d3bb7ff26

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [win]
  entry_points:
    - fermipy-dispatch = fermipy.scripts.dispatch:main
    - fermipy-clone-configs = fermipy.scripts.clone_configs:main
    - fermipy-collect-sources = fermipy.scripts.collect_sources:main
    - fermipy-cluster-sources = fermipy.scripts.cluster_sources:main
    - fermipy-flux-sensitivity = fermipy.scripts.flux_sensitivity:main
    - fermipy-run-tempo = fermipy.scripts.run_tempo:main
    - fermipy-select = fermipy.scripts.select_data:main
    - fermipy-validate = fermipy.scripts.validate:main
    - fermipy-coadd = fermipy.merge_utils:main
    
requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.6.1
    - astropy >=1.2.1
    - matplotlib >=1.5.0
    - scipy >=0.14
    - pyyaml
    - healpy
    - wcsaxes

test:
  imports:
    - fermipy

about:
  home: https://github.com/fermiPy/fermipy
  license:  BSD 3-Clause
  summary: "Fermipy is a python package for analysis of Fermi-LAT data"
  license_file: licenses/LICENSE.rst
  doc_url: http://fermipy.readthedocs.io
  dev_url: https://github.com/fermiPy/fermipy

extra:
  recipe-maintainers:
    - woodmd
