travis:
  secure:
    BINSTAR_TOKEN: vce6OWCWgBhz+lXX/3Hz/CZstKVMGwEjUsq4Ehvz6J4raNygevcyO7xGRa0ayP2+HEjmRLgm0flWSeFCZ1NvF6sUa0Gc40VQ7mJdvzJecJjRn9Pkl2+9jFRTaF9hw41ggRqvmWDL6GZNLnLsO9tTHLersc6qb+UbYP3JAk+9qSsgNkx/Cm8tkXYocN2r6Ay8j1uaDzXHyQkAypHUkwzxijRpeRGX+NchpdsWLx6SUJLY2fhc8x1Ovefy5ZztQ+YxoUUuPHgbh3ndFAi87R2WHIX7btvci3QWmpHQToFbTf8jLBy1gyzVm0hzNSTXkCB/7YDyGa68rbul0dGAlLy3dTOV7CxWT1he7npCO12TZc54hLA57BezRT9m4O4lOhcKTasLDVa77YRTtPBf1d8AJOfWmEtuTSRsBzPY1+7OGo2oz+O0pk4bWp1cmSH4QfIFbUpVrmqnsPFEsjuAt+EzBbEoYri2x3/00Zbn3cNdVdqtG2hkY3D06wrYNlXZQF8FNTNjWD0IEarRFMydoZk/CwRjiA3DOJnLK6z0jbCMsVZuEx3gZ43sBqjFJ1HZX0lk4sKsaZWqFQzwLip84xRxPhUhK/emx+ExSZc/fhifk0Bk87a/mz66krOoXP5Vud4kukkuvzSGAY6CdExHhosWgCuL5pHEoouBR3CxWelOs0A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
